# ----------------------------------------------
# Script Recorded by ANSYS Electronics Desktop Version 2021.1.0
# 15:16:22  Nov 29, 2023
# ----------------------------------------------
import ScriptEnv
ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
oDesktop.RestoreWindow()
oProject = oDesktop.NewProject()
oProject.InsertDesign("HFSS", "HFSSDesign1", "HFSS Modal Network", "")

oProject.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:ProjectVariableTab",
			[
				"NAME:PropServers", 
				"ProjectVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:$PinH",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "3mm"
				],
				[
					"NAME:$PinRad",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "(0.85/2) mm"
				],
				[
					"NAME:$PTFERad",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "(4.19/2) mm"
				],
				[
					"NAME:$FittingRad",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "(5.19/2) mm"
				],
				[
					"NAME:$h",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "15mm"
				],
				[
					"NAME:$Wg",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "150mm"
				],
				[
					"NAME:$Lg",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "125mm"
				],
				[
					"NAME:$W",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "30mm"
				],
				[
					"NAME:$L",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "30mm"
				],
				[
					"NAME:$Ws",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "5mm"
				],
				[
					"NAME:$Ls",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "20mm"
				],
				[
					"NAME:$Ps",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "7.5mm"
				],
				[
					"NAME:$X",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "0mm"
				]
			]
		]
	])
oDesign = oProject.SetActiveDesign("HFSSDesign1")
oEditor = oDesign.SetActiveEditor("3D Modeler")
oEditor.CreateRectangle(
	[
		"NAME:RectangleParameters",
		"IsCovered:="		, True,
		"XStart:="		, "-$Wg/2",
		"YStart:="		, "-$Lg/2",
		"ZStart:="		, "0mm",
		"Width:="		, "$Wg",
		"Height:="		, "$Lg",
		"WhichAxis:="		, "Z"
	], 
	[
		"NAME:Attributes",
		"Name:="		, "GroundPlane",
		"Flags:="		, "",
		"Color:="		, "(255 255 0)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"vacuum\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])

oEditor.CreateCylinder(
	[
		"NAME:CylinderParameters",
		"XCenter:="		, "0mm",
		"YCenter:="		, "$X",
		"ZCenter:="		, "0mm",
		"Radius:="		, "$FittingRad",
		"Height:="		, "-$PinH",
		"WhichAxis:="		, "Z",
		"NumSides:="		, "0"
	], 
	[
		"NAME:Attributes",
		"Name:="		, "RFFitting",
		"Flags:="		, "",
		"Color:="		, "(255 255 143)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"copper\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])

oEditor.CreateCylinder(
	[
		"NAME:CylinderParameters",
		"XCenter:="		, "0mm",
		"YCenter:="		, "$X",
		"ZCenter:="		, "0mm",
		"Radius:="		, "$PTFERad",
		"Height:="		, "-$PinH",
		"WhichAxis:="		, "Z",
		"NumSides:="		, "0"
	], 
	[
		"NAME:Attributes",
		"Name:="		, "Cylinder3",
		"Flags:="		, "",
		"Color:="		, "(255 255 143)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"copper\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])

oEditor.Subtract(
	[
		"NAME:Selections",
		"Blank Parts:="		, "RFFitting,GroundPlane",
		"Tool Parts:="		, "Cylinder3"
	], 
	[
		"NAME:SubtractParameters",
		"KeepOriginals:="	, False
	])



oEditor.CreateCylinder(
	[
		"NAME:CylinderParameters",
		"XCenter:="		, "0mm",
		"YCenter:="		, "$X",
		"ZCenter:="		, "0mm",
		"Radius:="		, "$PTFERad",
		"Height:="		, "-$PinH",
		"WhichAxis:="		, "Z",
		"NumSides:="		, "0"
	], 
	[
		"NAME:Attributes",
		"Name:="		, "RFFittingDielectric",
		"Flags:="		, "",
		"Color:="		, "(192 192 192)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"Teflon (tm)\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])

oEditor.CreateCylinder(
	[
		"NAME:CylinderParameters",
		"XCenter:="		, "0mm",
		"YCenter:="		, "$X",
		"ZCenter:="		, "0mm",
		"Radius:="		, "$PinRad",
		"Height:="		, "-$PinH",
		"WhichAxis:="		, "Z",
		"NumSides:="		, "0"
	], 
	[
		"NAME:Attributes",
		"Name:="		, "Cylinder4",
		"Flags:="		, "",
		"Color:="		, "(255 255 143)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"copper\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])


oEditor.Subtract(
	[
		"NAME:Selections",
		"Blank Parts:="		, "RFFittingDielectric",
		"Tool Parts:="		, "Cylinder4"
	], 
	[
		"NAME:SubtractParameters",
		"KeepOriginals:="	, False
	])

oEditor.CreateCylinder(
	[
		"NAME:CylinderParameters",
		"XCenter:="		, "0mm",
		"YCenter:="		, "$X",
		"ZCenter:="		, "0mm",
		"Radius:="		, "$PinRad",
		"Height:="		, "-$PinH",
		"WhichAxis:="		, "Z",
		"NumSides:="		, "0"
	], 
	[
		"NAME:Attributes",
		"Name:="		, "RFFittingPin",
		"Flags:="		, "",
		"Color:="		, "(255 255 0)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"copper\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])

oEditor.CreateCylinder(
	[
		"NAME:CylinderParameters",
		"XCenter:="		, "0mm",
		"YCenter:="		, "$X",
		"ZCenter:="		, "0mm",
		"Radius:="		, "$PinRad",
		"Height:="		, "$h",
		"WhichAxis:="		, "Z",
		"NumSides:="		, "0"
	], 
	[
		"NAME:Attributes",
		"Name:="		, "AntennaFeed",
		"Flags:="		, "",
		"Color:="		, "(255 128 0)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"copper\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])

oEditor.CreateRectangle(
	[
		"NAME:RectangleParameters",
		"IsCovered:="		, True,
		"XStart:="		, "-$W/2",
		"YStart:="		, "-$L/2",
		"ZStart:="		, "$h",
		"Width:="		, "$W",
		"Height:="		, "$L",
		"WhichAxis:="		, "Z"
	], 
	[
		"NAME:Attributes",
		"Name:="		, "EAntenna",
		"Flags:="		, "",
		"Color:="		, "(255 128 0)",
		"Transparency:="	, 0.2,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"vacuum\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])



oEditor.CreateRectangle(
	[
		"NAME:RectangleParameters",
		"IsCovered:="		, True,
		"XStart:="		, "$Ps-$Ws/2",
		"YStart:="		, "$L/2",
		"ZStart:="		, "$h",
		"Width:="		, "$Ws",
		"Height:="		, "-$Ls",
		"WhichAxis:="		, "Z"
	], 
	[
		"NAME:Attributes",
		"Name:="		, "Rectangle1",
		"Flags:="		, "",
		"Color:="		, "(143 175 143)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"vacuum\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])
    
    
oEditor.CreateRectangle(
	[
		"NAME:RectangleParameters",
		"IsCovered:="		, True,
		"XStart:="		, "-$Ps-$Ws/2",
		"YStart:="		, "$L/2",
		"ZStart:="		, "$h",
		"Width:="		, "$Ws",
		"Height:="		, "-$Ls",
		"WhichAxis:="		, "Z"
	], 
	[
		"NAME:Attributes",
		"Name:="		, "Rectangle2",
		"Flags:="		, "",
		"Color:="		, "(143 175 143)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"vacuum\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])

oEditor.Subtract(
	[
		"NAME:Selections",
		"Blank Parts:="		, "EAntenna",
		"Tool Parts:="		, "Rectangle1,Rectangle2"
	], 
	[
		"NAME:SubtractParameters",
		"KeepOriginals:="	, False
	])
    
 
# draw the pin for the port 
    
oEditor.CreateCircle(
	[
		"NAME:CircleParameters",
		"IsCovered:="		, True,
		"XCenter:="		, "0mm",
		"YCenter:="		, "$X",
		"ZCenter:="		, "-$PinH",
		"Radius:="		, "$FittingRad",
		"WhichAxis:="		, "Z",
		"NumSegments:="		, "0"
	], 
	[
		"NAME:Attributes",
		"Name:="		, "port",
		"Flags:="		, "",
		"Color:="		, "(225 128 128)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"vacuum\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])
















oModule = oDesign.GetModule("BoundarySetup")
oModule.AssignFiniteCond(
	[
		"NAME:FiniteCond1",
		"Objects:="		, ["GroundPlane"],
		"UseMaterial:="		, True,
		"Material:="		, "copper",
		"UseThickness:="	, False,
		"Roughness:="		, "0um",
		"InfGroundPlane:="	, False,
		"IsTwoSided:="		, False,
		"IsInternal:="		, True
	])

oModule.AssignFiniteCond(
	[
		"NAME:FiniteCond2",
		"Objects:="		, ["EAntenna"],
		"UseMaterial:="		, True,
		"Material:="		, "copper",
		"UseThickness:="	, False,
		"Roughness:="		, "0um",
		"InfGroundPlane:="	, False,
		"IsTwoSided:="		, False,
		"IsInternal:="		, True
	])


# generic lumped approach 

#INSERT_PORT_SETUP

oModule.AssignLumpedPort(
	[
		"NAME:1",
		"Objects:="		, ["Circle1"],
		"DoDeembed:="		, False,
		"RenormalizeAllTerminals:=", True,
		[
			"NAME:Modes",
			[
				"NAME:Mode1",
				"ModeNum:="		, 1,
				"UseIntLine:="		, True,
				[
					"NAME:IntLine",
					"Start:="		, ["-0.425mm","-5.20474889637625e-17mm","-3mm"],
					"End:="			, ["-2.095mm","-2.5656350442137e-16mm","-3mm"]
				],
				"AlignmentGroup:="	, 0,
				"CharImp:="		, "Zpi",
				"RenormImp:="		, "50ohm"
			]
		],
		"ShowReporterFilter:="	, False,
		"ReporterFilter:="	, [True],
		"Impedance:="		, "50ohm"
	])




## assign radiation box (alternative to the airbox setup
oModule = oDesign.GetModule("ModelSetup")
oModule.CreateOpenRegion(
	[
		"NAME:Settings",
		"OpFreq:="		, "1.8GHz",
		"Boundary:="		, "Radiation",
		"ApplyInfiniteGP:="	, False
	])









## Sim setup script takes over here


oModule = oDesign.GetModule("RadField")
oModule.InsertInfiniteSphereSetup(
	[
		"NAME:Infinite Sphere1",
		"UseCustomRadiationSurface:=", False,
		"CSDefinition:="	, "Theta-Phi",
		"Polarization:="	, "Linear",
		"ThetaStart:="		, "0deg",
		"ThetaStop:="		, "180deg",
		"ThetaStep:="		, "2deg",
		"PhiStart:="		, "-180deg",
		"PhiStop:="		, "180deg",
		"PhiStep:="		, "2deg",
		"UseLocalCS:="		, False
	])
oModule.InsertSphereSetup(
	[
		"NAME:Sphere1",
		"UseCustomRadiationSurface:=", False,
		"Radius:="		, "20mm",
		"ThetaStart:="		, "0deg",
		"ThetaStop:="		, "180deg",
		"ThetaStep:="		, "2deg",
		"PhiStart:="		, "-180deg",
		"PhiStop:="		, "180deg",
		"PhiStep:="		, "2deg",
		"UseLocalCS:="		, False
	])





oModule = oDesign.GetModule("AnalysisSetup")
oModule.InsertSetup("HfssDriven", 
	[
		"NAME:Setup1",
		"SolveType:="		, "MultiFrequency",
		[
			"NAME:MultipleAdaptiveFreqsSetup",
			[
				"NAME:AdaptAt",
				"Frequency:="		, "1.8GHz",
				"Delta:="		, 0.02
			],
			[
				"NAME:AdaptAt",
				"Frequency:="		, "2.4GHz",
				"Delta:="		, 0.02
			]
		],
		"MaximumPasses:="	, 6,
		"MinimumPasses:="	, 1,
		"MinimumConvergedPasses:=", 1,
		"PercentRefinement:="	, 30,
		"IsEnabled:="		, True,
		[
			"NAME:MeshLink",
			"ImportMesh:="		, False
		],
		"BasisOrder:="		, 1,
		"DoLambdaRefine:="	, True,
		"DoMaterialLambda:="	, True,
		"SetLambdaTarget:="	, False,
		"Target:="		, 0.3333,
		"UseMaxTetIncrease:="	, False,
		"PortAccuracy:="	, 2,
		"UseABCOnPort:="	, False,
		"SetPortMinMaxTri:="	, False,
		"UseDomains:="		, False,
		"UseIterativeSolver:="	, False,
		"SaveRadFieldsOnly:="	, False,
		"SaveAnyFields:="	, True,
		"IESolverType:="	, "Auto",
		"LambdaTargetForIESolver:=", 0.15,
		"UseDefaultLambdaTgtForIESolver:=", True,
		"IE Solver Accuracy:="	, "Balanced"
	])
oModule.InsertFrequencySweep("Setup1", 
	[
		"NAME:Sweep",
		"IsEnabled:="		, True,
		"RangeType:="		, "LinearCount",
		"RangeStart:="		, "1.4GHz",
		"RangeEnd:="		, "3GHz",
		"RangeCount:="		, 401,
		"Type:="		, "Interpolating",
		"SaveFields:="		, True,
		"SaveRadFields:="	, False,
		"InterpTolerance:="	, 0.5,
		"InterpMaxSolns:="	, 250,
		"InterpMinSolns:="	, 0,
		"InterpMinSubranges:="	, 1,
		"InterpUseS:="		, True,
		"InterpUsePortImped:="	, False,
		"InterpUsePropConst:="	, True,
		"UseDerivativeConvergence:=", False,
		"InterpDerivTolerance:=", 0.2,
		"UseFullBasis:="	, True,
		"EnforcePassivity:="	, True,
		"PassivityErrorTolerance:=", 0.0001
	])



oDesign.AnalyzeAll()













## Generate reports


oModule = oDesign.GetModule("ReportSetup")
oModule.CreateReport("S Parameter Plot 1", "Modal Solution Data", "Rectangular Plot", "Setup1 : Sweep", 
	[
		"Domain:="		, "Sweep"
	], 
	[
		"Freq:="		, ["All"],
		"$PinH:="		, ["Nominal"],
		"$h:="			, ["Nominal"],
		"$Wg:="			, ["Nominal"],
		"$Lg:="			, ["Nominal"],
		"$W:="			, ["Nominal"],
		"$L:="			, ["Nominal"],
		"$Ws:="			, ["Nominal"],
		"$Ls:="			, ["Nominal"],
		"$Ps:="			, ["Nominal"],
		"$X:="			, ["Nominal"]
	], 
	[
		"X Component:="		, "Freq",
		"Y Component:="		, ["dB(S(1,1))"]
	])
oModule.CreateReport("Antenna Params Table 1", "Antenna Parameters", "Data Table", "Setup1 : LastAdaptive", 
	[
		"Context:="		, "3D"
	], 
	[
		"Freq:="		, ["All"],
		"$PinH:="		, ["Nominal"],
		"$h:="			, ["Nominal"],
		"$Wg:="			, ["Nominal"],
		"$Lg:="			, ["Nominal"],
		"$W:="			, ["Nominal"],
		"$L:="			, ["Nominal"],
		"$Ws:="			, ["Nominal"],
		"$Ls:="			, ["Nominal"],
		"$Ps:="			, ["Nominal"],
		"$X:="			, ["Nominal"]
	], 
	[
		"X Component:="		, "Freq",
		"Y Component:="		, ["dB(PeakDirectivity)"]
	])
oModule.AddTraces("Antenna Params Table 1", "Setup1 : LastAdaptive", 
	[
		"Context:="		, "3D"
	], 
	[
		"Freq:="		, ["All"],
		"$PinH:="		, ["Nominal"],
		"$h:="			, ["Nominal"],
		"$Wg:="			, ["Nominal"],
		"$Lg:="			, ["Nominal"],
		"$W:="			, ["Nominal"],
		"$L:="			, ["Nominal"],
		"$Ws:="			, ["Nominal"],
		"$Ls:="			, ["Nominal"],
		"$Ps:="			, ["Nominal"],
		"$X:="			, ["Nominal"]
	], 
	[
		"X Component:="		, "Freq",
		"Y Component:="		, ["dB(PeakGain)"]
	])
oModule.AddTraces("Antenna Params Table 1", "Setup1 : LastAdaptive", 
	[
		"Context:="		, "3D"
	], 
	[
		"Freq:="		, ["All"],
		"$PinH:="		, ["Nominal"],
		"$h:="			, ["Nominal"],
		"$Wg:="			, ["Nominal"],
		"$Lg:="			, ["Nominal"],
		"$W:="			, ["Nominal"],
		"$L:="			, ["Nominal"],
		"$Ws:="			, ["Nominal"],
		"$Ls:="			, ["Nominal"],
		"$Ps:="			, ["Nominal"],
		"$X:="			, ["Nominal"]
	], 
	[
		"X Component:="		, "Freq",
		"Y Component:="		, ["RadiationEfficiency"]
	])
oModule.AddTraces("Antenna Params Table 1", "Setup1 : LastAdaptive", 
	[
		"Context:="		, "3D"
	], 
	[
		"Freq:="		, ["All"],
		"$PinH:="		, ["Nominal"],
		"$h:="			, ["Nominal"],
		"$Wg:="			, ["Nominal"],
		"$Lg:="			, ["Nominal"],
		"$W:="			, ["Nominal"],
		"$L:="			, ["Nominal"],
		"$Ws:="			, ["Nominal"],
		"$Ls:="			, ["Nominal"],
		"$Ps:="			, ["Nominal"],
		"$X:="			, ["Nominal"]
	], 
	[
		"X Component:="		, "Freq",
		"Y Component:="		, ["BeamArea"]
	])
